language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yasuhiro/react-news -f Dockerfile.dev .

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: "react-news"
  env: "ReactNews-env"
  bucket_name: "elasticbeanstalk-us-east-1-360399115248"
  bucket_path: "react-news"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"