sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yasuhiro/news-react -f Dockerfile.dev .

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: "news-react"
  env: "NewsReact-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-1-360399115248"
  bucket_path: "news-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"